"""feat(migration): create users table

Revision ID: 1dce04817066
Revises: 
Create Date: 2025-01-11 00:14:01.337659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dce04817066'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radiographs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tasks', sa.String(length=50), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('original', sa.String(length=255), nullable=False),
    sa.Column('status_detection', sa.Enum('success', 'in progress', 'failed', name='status_enum'), nullable=False),
    sa.Column('predicted', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tasks')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('radiographs')
    # ### end Alembic commands ###
