"""drop predicted column from radiographs

Revision ID: 4e6380b14183
Revises: ee159b721e56
Create Date: 2025-05-17 16:15:58.867925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6380b14183'
down_revision: Union[str, None] = 'ee159b721e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radiographs', 'predicted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radiographs', sa.Column('predicted', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
