"""Add overlay column to radiographs

Revision ID: a896d9dc8d2d
Revises: 242f7d2580d3
Create Date: 2025-04-16 09:51:47.448292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a896d9dc8d2d'
down_revision: Union[str, None] = '242f7d2580d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
