"""add expires_at to token_blacklist

Revision ID: cc893fd61fb5
Revises: abb10ccaa8b5
Create Date: 2025-01-13 21:29:25.419870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc893fd61fb5'
down_revision: Union[str, None] = 'abb10ccaa8b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_blacklist', 'expires_at')
    # ### end Alembic commands ###
