"""Add mask_file column to radiographs table

Revision ID: ee159b721e56
Revises: a9e1a72e1535
Create Date: 2025-05-17 15:48:16.336529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee159b721e56'
down_revision: Union[str, None] = 'a9e1a72e1535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('radiographs', sa.Column('mask_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radiographs', 'mask_file')
    # ### end Alembic commands ###
